#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

TAURI_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/tauri"
LINUXDEPLOY="${LINUXDEPLOY:-$TAURI_CACHE_DIR/linuxdeploy-x86_64.AppImage}"
GTK_PLUGIN="${GTK_PLUGIN:-$TAURI_CACHE_DIR/linuxdeploy-plugin-gtk.sh}"
APPIMAGE_PLUGIN="${APPIMAGE_PLUGIN:-$TAURI_CACHE_DIR/linuxdeploy-plugin-appimage.AppImage}"
BUNDLE_DIR="$PROJECT_ROOT/src-tauri/target/release/bundle/appimage"
APPDIR="$BUNDLE_DIR/atiga-cine.AppDir"

download_tool() {
  local destination="$1"
  local url="$2"

  if [[ -f "$destination" ]]; then
    chmod +x "$destination"
    return
  fi

  if ! command -v curl >/dev/null 2>&1; then
    echo "curl is required to download AppImage build tools" >&2
    exit 1
  fi

  mkdir -p "$(dirname "$destination")"
  echo "Downloading $(basename "$destination")..."
  curl --fail --location --silent --show-error --retry 3 --retry-delay 2 \
    "$url" --output "$destination.download"
  chmod +x "$destination.download"
  mv "$destination.download" "$destination"
}

download_tool \
  "$LINUXDEPLOY" \
  "https://github.com/tauri-apps/binary-releases/releases/download/linuxdeploy/linuxdeploy-x86_64.AppImage"
download_tool \
  "$GTK_PLUGIN" \
  "https://raw.githubusercontent.com/tauri-apps/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh"
download_tool \
  "$APPIMAGE_PLUGIN" \
  "https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage"

# linuxdeploy spends a long time asking dpkg for copyright metadata for every
# copied library. The metadata is unrelated to runtime loading and can make
# AppImage builds appear hung on Debian based systems, so make those lookups
# fail quickly. Application licensing remains in the repository and package
# metadata generated by Tauri is still built normally.
BUILD_TOOLS_DIR="$(mktemp -d)"
PATCHED_GTK_PLUGIN=""
cleanup() {
  rm -rf "$BUILD_TOOLS_DIR"
  if [[ -n "$PATCHED_GTK_PLUGIN" ]]; then
    rm -f "$PATCHED_GTK_PLUGIN"
  fi
}
trap cleanup EXIT

cat > "$BUILD_TOOLS_DIR/dpkg-query" <<'EOF'
#!/bin/sh
exit 1
EOF
chmod +x "$BUILD_TOOLS_DIR/dpkg-query"
export PATH="$BUILD_TOOLS_DIR:$PATH"

echo "Building Debian and RPM bundles to produce the release binary..."
pnpm exec tauri build --bundles deb,rpm

rm -rf "$APPDIR"
mkdir -p \
  "$APPDIR/usr/bin" \
  "$APPDIR/usr/lib/atiga-cine/lib" \
  "$APPDIR/usr/share/applications"

cp src-tauri/target/release/atiga-cine "$APPDIR/usr/lib/atiga-cine/atiga-cine.bin"
cp -a src-tauri/lib/. "$APPDIR/usr/lib/atiga-cine/lib/"

cat > "$APPDIR/usr/bin/atiga-cine" <<'EOF'
#!/bin/sh
set -eu

APPDIR="$(CDPATH= cd -- "$(dirname -- "$(readlink -f -- "$0")")/../.." && pwd)"
export APPDIR
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$APPDIR/usr/lib/x86_64-linux-gnu:$APPDIR/usr/lib/atiga-cine/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

for hook in "$APPDIR"/apprun-hooks/*.sh; do
  [ -f "$hook" ] || continue
  # shellcheck disable=SC1090
  . "$hook"
done

cd "$APPDIR/usr"
exec "$APPDIR/usr/lib/atiga-cine/atiga-cine.bin" "$@"
EOF
chmod +x "$APPDIR/usr/bin/atiga-cine"

# WebKitGTK loads these helper processes by absolute relative paths at
# runtime; they are not ELF dependencies of the main Tauri binary, so
# linuxdeploy cannot discover them from the executable alone.
WEBKIT_HELPER_DIR=""
for candidate in /usr/lib/*/webkit2gtk-4.1 /usr/lib64/webkit2gtk-4.1; do
  if [[ -d "$candidate" ]]; then
    WEBKIT_HELPER_DIR="$candidate"
    break
  fi
done
if [[ -z "$WEBKIT_HELPER_DIR" ]]; then
  echo "Could not find the WebKitGTK helper directory" >&2
  exit 1
fi
WEBKIT_HELPER_RELATIVE="${WEBKIT_HELPER_DIR#/}"
mkdir -p "$APPDIR/$WEBKIT_HELPER_RELATIVE/injected-bundle"
for helper in WebKitNetworkProcess WebKitWebProcess; do
  cp -a "$WEBKIT_HELPER_DIR/$helper" "$APPDIR/$WEBKIT_HELPER_RELATIVE/"
done
cp -a "$WEBKIT_HELPER_DIR/injected-bundle/." \
  "$APPDIR/$WEBKIT_HELPER_RELATIVE/injected-bundle/"

sed \
  -e 's/{{comment}}/Native Linux media player/' \
  -e 's/{{exec}}/atiga-cine/' \
  -e 's/{{categories}}/AudioVideo;Video;/' \
  src-tauri/packaging/atiga-cine.desktop.hbs \
  > "$APPDIR/usr/share/applications/atiga-cine.desktop"
cp src-tauri/icons/512x512.png "$APPDIR/atiga-cine.png"

echo "Deploying ELF dependencies without the recursive GTK scan..."
APPIMAGE_EXTRACT_AND_RUN=1 "$LINUXDEPLOY" \
  --appimage-extract-and-run \
  --verbosity "${LINUXDEPLOY_VERBOSITY:-1}" \
  --appdir "$APPDIR" \
  --executable "$APPDIR/usr/lib/atiga-cine/atiga-cine.bin" \
  --desktop-file "$APPDIR/usr/share/applications/atiga-cine.desktop" \
  --icon-file "$APPDIR/atiga-cine.png"

# The current GTK plugin performs a second linuxdeploy pass for libraries
# already handled above. That pass is the part that stalls on this system.
# Keep the resource setup and runtime hook from the plugin, but skip only that
# redundant dependency scan.
PATCHED_GTK_PLUGIN="$BUILD_TOOLS_DIR/linuxdeploy-plugin-gtk.sh"
sed \
  '/env LINUXDEPLOY_PLUGIN_MODE=1 "\$LINUXDEPLOY" --appdir="\$APPDIR" "\${LIBRARIES\[@\]}"/s/^/# skipped redundant GTK dependency scan: /' \
  "$GTK_PLUGIN" > "$PATCHED_GTK_PLUGIN"
chmod +x "$PATCHED_GTK_PLUGIN"

echo "Installing GTK runtime resources..."
APPIMAGE_EXTRACT_AND_RUN=1 \
  LINUXDEPLOY="$LINUXDEPLOY" \
  "$PATCHED_GTK_PLUGIN" --appdir "$APPDIR"

# appimagetool keeps an existing AppRun symlink and uses the desktop entry's
# Exec value as its target. The wrapper then starts the real binary from the
# resource directory after preparing the AppImage runtime environment.
ln -sfn usr/bin/atiga-cine "$APPDIR/AppRun"

echo "Creating AppImage..."
rm -f "$BUNDLE_DIR/Atiga_Cine-x86_64.AppImage"
(
  cd "$BUNDLE_DIR"
  APPIMAGE_EXTRACT_AND_RUN=1 "$APPIMAGE_PLUGIN" --appdir "$APPDIR"
)

GENERATED_APPIMAGE="$(find "$BUNDLE_DIR" -maxdepth 1 -type f -name '*-x86_64.AppImage' -print -quit)"
if [[ -z "$GENERATED_APPIMAGE" ]]; then
  echo "appimagetool did not produce an AppImage" >&2
  exit 1
fi

VERSION="$(sed -n 's/^[[:space:]]*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' src-tauri/tauri.conf.json | head -1)"
OUTPUT="$BUNDLE_DIR/atiga-cine_${VERSION}_amd64.AppImage"
mv "$GENERATED_APPIMAGE" "$OUTPUT"
chmod +x "$OUTPUT"

echo "Created $OUTPUT"
